[package]
name = "rayon_iter_concurrent_limit"
version = "0.3.0"
authors = ["Lachlan Deakin <ljdgit@gmail.com>"]
edition = "2021"
rust-version = "1.75"
description = "Limit the concurrency of a rayon parallel iterator with a convenient extension trait"
documentation = "https://docs.rs/rayon_iter_concurrent_limit"
repository = "https://github.com/LDeakin/rayon_iter_concurrent_limit"
license = "MIT OR Apache-2.0"
keywords = ["rayon", "iterator", "concurrency"]
categories = ["concurrency"]
exclude = [".github"]

[dependencies]
rayon = "1.8"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "concurrent_limit"
harness = false
